### ISSUE TITLE
Problem after last update

### ISSUE THREAD

**Issue by Stef1972** [dwaan/homebridge-adb#34]
After the last update the process is starting and restarting in a loop. This is the log:

[05/03/2021, 17:04:38] [homebridge-adb] Restarting Process...
Initializing HAP-NodeJS v0.9.2...
[05/03/2021, 17:04:39] [homebridge-adb] Launched child bridge with PID 30683
[05/03/2021, 17:04:39] Registering platform 'homebridge-adb.HomebridgeADB'
[05/03/2021, 17:04:39] [homebridge-adb] Loaded homebridge-adb v1.3.0 child bridge successfully
[05/03/2021, 17:04:40] Loaded 0 cached accessories from cachedAccessories.0EB39273332F.
Preparing Advertiser for 'homebridge-adb 6BA7' using bonjour-hap backend!
[05/03/2021, 17:04:40] [homebridge-adb] Creating: FireStick
[FireStick@@Volume] Characteristic not in required or optional characteristic section for service Television. Adding anyway.
Starting to advertise 'homebridge-adb 6BA7' using bonjour-hap backend!
[05/03/2021, 17:04:40] Homebridge v1.3.2 (homebridge-adb) is running on port 55246.
[05/03/2021, 17:04:40] [homebridge-adb] 
Can't get information from 'FireStick'.
This shouldn't be a problem, but please report this output.
1. When running this command
adb -s 192.168.1.207 shell "getprop ro.product.model && getprop ro.product.manufacturer && getprop ro.serialno"
2. Output:

3. Error output:
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.

Preparing Advertiser for 'FireStick B436' using bonjour-hap backend!
Starting to advertise 'FireStick B436' using bonjour-hap backend!
[05/03/2021, 17:04:40] FireStick B436 is running on port 38277.
[05/03/2021, 17:04:40] Please add [FireStick B436] manually in Home app. Setup Code: 777-63-818
[05/03/2021, 17:04:43] [homebridge-adb] FireStick - Sending: PAUSE
[05/03/2021, 17:04:43] [homebridge-adb] FireStick - Awake
TypeError: Cannot read property 'includes' of undefined
    at /usr/local/lib/node_modules/homebridge-adb/index.js:516:21
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
[05/03/2021, 17:04:45] [homebridge-adb] Child bridge process ended
[05/03/2021, 17:04:45] [homebridge-adb] Process Ended. Code: 1, Signal: null

**Comment by dwaan** [comment]
Please check if the newer version is working now.

**Comment by Stef1972** [comment]
it seems it works !

**Comment by dwaan** [comment]
Thank you for testing as my device didn’t experience the error. If it doesn’t work again, you can open new issue.
