### ISSUE TITLE
Plugin makes Homebridge reboot

### ISSUE THREAD

**Issue by Stef1972** [dwaan/homebridge-adb#37]
Hi
today I have experienced this issue. All was working fine until I finish to play a movie on Disnay+ app and I turned off the fire stick. At that point homebridge restarted diplaing this error:

[13/03/2021, 19:03:12] TypeError: Cannot read property 'split' of undefined
    at /usr/local/lib/node_modules/homebridge-adb/index.js:609:27
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
[13/03/2021, 19:03:12] Got SIGTERM, shutting down child bridge process...
[13/03/2021, 19:03:12] Got SIGTERM, shutting down child bridge process...

From that moment it was not possible to restart homebridge without disable homebridge-adb plugin.

So I disabled it and I installed the version 1.3.1 and I received the same problem.

While homebridge was stopping and restarting in a loop I turned on the fire stick and then I turned it off again. 

After that homebridge ends the loop and started correctly. I update to version 1.4.0 and all continue to work fine.

So, now it is working. I solved the problem turning on and off the fire stick : it seems that it sends some bad signals to the plugin...

I don't know if my explanation can help...

**Comment by dwaan** [comment]
Thank you, it's a very clear explanation, I'll try to fix this error in the next update.

**Comment by dwaan** [comment]
The latest update might solve this problem, please try it and let me know the result.
