### ISSUE TITLE
ADB wont start 

### ISSUE THREAD

**Issue by Alex565rf** [dwaan/homebridge-adb#9]
Hello,
I just install the ADB plugin on web version of homebridge. When i config my tv with the IP, the homebrige server don't whant to restart and give me this:

TypeError: Cannot read property 'log' of undefined
    at error (/usr/local/lib/node_modules/homebridge-adb/index.js:520:9)
    at /usr/local/lib/node_modules/homebridge-adb/index.js:545:6
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)

Did you have a solution for it ? 
Thank's a lot
![Capture d’écran 2020-09-14 à 21 21 00](https://user-images.githubusercontent.com/71288814/93128745-41746900-f6d0-11ea-9c8b-7ec03c648828.png)

**Comment by facutopa** [comment]
Same here
```
[9/14/2020, 18:08:02] TypeError: Cannot read property 'log' of undefined
    at error (/usr/local/lib/node_modules/homebridge-adb/index.js:520:9)
    at /usr/local/lib/node_modules/homebridge-adb/index.js:545:6
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12)

[9/14/2020, 18:08:02] Got SIGTERM, shutting down Homebridge...
[9/14/2020, 18:08:05] [Config] Terminal session ended.
```

**Comment by Alex565rf** [comment]
I only got the tuya web plugin

**Comment by Alex565rf** [comment]
I got it to work, it was because of bad installation off android sdk.

do it: https://stackoverflow.com/questions/31374085/installing-adb-on-macos

**Comment by facutopa** [comment]
Yep, solved with adb commands, thanks
