### ISSUE TITLE
Latest update 2.2.1 preventing Homebridge from starting

### ISSUE THREAD

**Issue by danfratamico** [dwaan/homebridge-adb#98]
I upgraded to 2.2.1 a few days ago and when I reboot Homebridge I am getting the below errors. If I remove my configured accessory (streaming stick) and restart, the error goes away. If I add the accessory and restart, issue returns.

```
[8/7/2023, 8:38:35 AM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge) is running on port 51360.
[8/7/2023, 8:38:35 AM] Bedroom Fire TV XXX is running on port 41279.
[8/7/2023, 8:38:35 AM] Please add [Bedroom Fire TV XXX] manually in Home app. Setup Code: XXX
[8/7/2023, 8:38:35 AM] TypeError: The argument 'file' cannot be empty. Received ''
    at new NodeError (node:internal/errors:405:5)
    at normalizeSpawnArguments (node:child_process:549:11)
    at spawn (node:child_process:750:13)
    at execFile (node:child_process:348:17)
    at tryCatcher (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Connection._exec (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/@devicefarmer/adbkit/src/adb/connection.ts:104:16)
    at Connection.startServer (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/@devicefarmer/adbkit/src/adb/connection.ts:93:17)
    at /var/lib/homebridge/node_modules/homebridge-adb/node_modules/@devicefarmer/adbkit/src/adb/connection.ts:45:23
    at tryCatcher (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/bluebird/js/release/async.js:86:9)
```

**Comment by dwaan** [comment]
Thank you for the report, it looks like the new stack is causing some error. In the meantime please use previous working version while I'm working the bug fix.

**Comment by aarnaegg** [comment]
Just curious on a possible fix in a 2.2.3?
2.2.2 prevents Homebridge from starting on my setup as well.

**Comment by danfratamico** [comment]
FYI - I'm still seeing issues on v2.2.5. Had to disable the plugin to prevent Homebridge from restarting every few minutes.

**Comment by dwaan** [comment]
> FYI - I'm still seeing issues on v2.2.5. Had to disable the plugin to prevent Homebridge from restarting every few minutes.

What’s the error output right now?

**Comment by danfratamico** [comment]
```
[9/25/2023, 1:06:18 PM] Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:962:11)
    at Socket._write (node:net:974:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.Writable.write (node:internal/streams/writable:337:10)
    at /var/lib/homebridge/node_modules/homebridge-adb/node_modules/nodejs-adb-wrapper/index.js:230:36
    at new Promise (<anonymous>)
    at _connect (/var/lib/homebridge/node_modules/homebridge-adb/node_modules/nodejs-adb-wrapper/index.js:180:20)
```

**Comment by Goldsucher** [comment]
any news on this?
